<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('jobs')->insert([
            [
                'admin_id' => 1,
                'title' => 'Frontend Developer',
                'description' => 'We are looking for a skilled frontend developer with experience in HTML, CSS, JavaScript, and modern frameworks like React, Vue.js, or Angular. You will be responsible for building responsive web applications and collaborating with our design team.',
                'location' => 'Bangkok, Thailand',
                'salary' => 45000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Backend Developer',
                'description' => 'Work with Laravel and MySQL to build scalable backend systems for our job platform. Experience with RESTful APIs, database optimization, and cloud services is required.',
                'location' => 'Remote',
                'salary' => 55000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'UI/UX Designer',
                'description' => 'Design clean and modern interfaces for web and mobile applications. You will work closely with developers to create intuitive user experiences and beautiful visual designs.',
                'location' => 'Tokyo, Japan',
                'salary' => 60000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Digital Marketing Specialist',
                'description' => 'Manage social media, SEO, and content marketing campaigns for our clients. Experience with Google Analytics, Facebook Ads, and content creation is essential.',
                'location' => 'Singapore',
                'salary' => 50000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Full Stack Developer',
                'description' => 'Join our team as a full stack developer working with both frontend and backend technologies. You will develop end-to-end features and maintain our existing codebase.',
                'location' => 'New York, USA',
                'salary' => 75000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'DevOps Engineer',
                'description' => 'Manage our cloud infrastructure, CI/CD pipelines, and deployment processes. Experience with AWS, Docker, Kubernetes, and automation tools required.',
                'location' => 'London, UK',
                'salary' => 70000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Data Scientist',
                'description' => 'Analyze large datasets to extract insights and build predictive models. Proficiency in Python, R, machine learning, and statistical analysis is required.',
                'location' => 'San Francisco, USA',
                'salary' => 90000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Mobile App Developer',
                'description' => 'Develop native and cross-platform mobile applications for iOS and Android. Experience with React Native, Flutter, or Swift/Kotlin is preferred.',
                'location' => 'Sydney, Australia',
                'salary' => 65000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Product Manager',
                'description' => 'Lead product development initiatives, work with cross-functional teams, and define product roadmaps. Strong analytical and communication skills required.',
                'location' => 'Berlin, Germany',
                'salary' => 80000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'QA Engineer',
                'description' => 'Design and execute test plans, perform manual and automated testing, and ensure product quality. Experience with testing frameworks and bug tracking tools.',
                'location' => 'Toronto, Canada',
                'salary' => 55000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Cybersecurity Analyst',
                'description' => 'Protect our systems from security threats, conduct security audits, and implement security best practices. Certifications like CISSP or CEH are a plus.',
                'location' => 'Remote',
                'salary' => 85000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Content Writer',
                'description' => 'Create engaging content for blogs, social media, and marketing materials. Strong writing skills and SEO knowledge are essential.',
                'location' => 'Dublin, Ireland',
                'salary' => 40000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Sales Representative',
                'description' => 'Build relationships with clients, identify sales opportunities, and achieve sales targets. Excellent communication and negotiation skills required.',
                'location' => 'Dubai, UAE',
                'salary' => 45000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'HR Manager',
                'description' => 'Oversee recruitment, employee relations, and HR policies. Experience in talent acquisition and HR management systems is required.',
                'location' => 'Mumbai, India',
                'salary' => 50000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Business Analyst',
                'description' => 'Analyze business processes, gather requirements, and work with stakeholders to improve business operations. Strong analytical and problem-solving skills.',
                'location' => 'Amsterdam, Netherlands',
                'salary' => 60000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Graphic Designer',
                'description' => 'Create visual designs for marketing materials, websites, and branding. Proficiency in Adobe Creative Suite and design principles required.',
                'location' => 'Barcelona, Spain',
                'salary' => 45000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Database Administrator',
                'description' => 'Manage and optimize database systems, ensure data integrity, and perform backups. Experience with MySQL, PostgreSQL, or MongoDB required.',
                'location' => 'Seoul, South Korea',
                'salary' => 60000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Project Manager',
                'description' => 'Lead project teams, manage timelines and budgets, and ensure successful project delivery. PMP certification is a plus.',
                'location' => 'Paris, France',
                'salary' => 70000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Customer Support Specialist',
                'description' => 'Provide excellent customer service, resolve issues, and maintain customer satisfaction. Strong communication and problem-solving skills required.',
                'location' => 'Remote',
                'salary' => 35000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_id' => 1,
                'title' => 'Software Architect',
                'description' => 'Design system architecture, make technical decisions, and guide development teams. Extensive experience in software design patterns and scalability required.',
                'location' => 'Zurich, Switzerland',
                'salary' => 100000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
